# Generated by Django 3.2.16 on 2022-10-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='producer',
            new_name='name',
        ),
    ]
