# Generated by Django 3.2.16 on 2022-10-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0003_yarn'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
