# Generated by Django 3.2.16 on 2022-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0005_auto_20221030_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
