# Generated by Django 3.2.16 on 2022-10-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0007_auto_20221030_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_choice',
            field=models.CharField(choices=[('White', '1'), ('Yellow', '2'), ('Blue', '3'), ('Red', '4'), ('Green', '5'), ('Black', '6'), ('Brown', '7')], default='White', max_length=10),
        ),
    ]
