# Generated by Django 3.2.16 on 2022-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0008_alter_color_color_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.AlterField(
            model_name='color',
            name='color_choice',
            field=models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Black', 'Black'), ('Brown', 'Brown')], default='White', max_length=10),
        ),
    ]
