# Generated by Django 3.2.16 on 2022-10-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0009_auto_20221030_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('Wool', 'Wool'), ('Alpaca', 'Alpaca'), ('Cashmere', 'Cashmere')], default='Wool', max_length=10),
        ),
    ]
