# Generated by Django 3.2.16 on 2022-11-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0013_yarn_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_choice',
            field=models.CharField(choices=[('Wh', 'White'), ('Ye', 'Yellow'), ('Bl', 'Blue'), ('Re', 'Red'), ('Gr', 'Green'), ('Bl', 'Black'), ('Br', 'Brown')], default='Wh', max_length=10),
        ),
    ]
