# Generated by Django 3.2.16 on 2022-11-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0014_alter_color_color_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='exists',
        ),
        migrations.AddField(
            model_name='yarn',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
