# Generated by Django 3.2.16 on 2022-11-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0016_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_choice', models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Black', 'Black'), ('Brown', 'Brown'), ('Purple', 'Purple'), ('Gray', 'Gray')], default='White', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='yarn',
            name='color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stash.colorgroup'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
