# Generated by Django 3.2.16 on 2022-11-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0017_auto_20221106_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorgroup',
            name='color_choice',
            field=models.CharField(choices=[('WHITE', 'White'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('RED', 'Red'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('BROWN', 'Brown'), ('PURPLE', 'Purple'), ('GRAY', 'Gray')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stash.colorgroup'),
        ),
    ]
