# Generated by Django 3.2.16 on 2022-11-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0018_auto_20221107_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='color',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ColorGroup',
        ),
    ]
