# Generated by Django 3.2.16 on 2022-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0019_auto_20221107_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
