# Generated by Django 3.2.16 on 2022-11-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0022_auto_20221107_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='material',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
