# Generated by Django 3.2.16 on 2022-11-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0023_auto_20221107_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='favorite',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
