# Generated by Django 3.2.16 on 2022-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0024_auto_20221107_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='color_code',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
