# Generated by Django 3.2.16 on 2022-11-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0025_yarn_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yarn',
            old_name='color',
            new_name='color_group',
        ),
    ]
