# Generated by Django 3.2.16 on 2022-11-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0027_yarn_frogged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='frogged',
            new_name='finished',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
