# Generated by Django 3.2.16 on 2022-11-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0028_auto_20221110_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
