# Generated by Django 3.2.16 on 2022-11-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0030_auto_20221111_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='yarn',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stash.yarn'),
        ),
    ]
