# Generated by Django 3.2.16 on 2022-11-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0031_alter_project_yarn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='yarn',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stash.yarn'),
        ),
    ]
