# Generated by Django 3.2.16 on 2022-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0032_alter_project_yarn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='color_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='color_group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
