# Generated by Django 3.2.16 on 2022-11-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0034_auto_20221112_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
