# Generated by Django 3.2.16 on 2022-11-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0035_alter_yarn_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, verbose_name='Notes about the project:'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Is the project finished?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='Link to pattern:'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of the Yarn'),
        ),
        migrations.AlterField(
            model_name='project',
            name='yarn',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stash.yarn', verbose_name='Yarn in this project:'),
        ),
    ]
