# Generated by Django 3.2.16 on 2022-11-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0036_auto_20221113_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, verbose_name='Notes about the project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='Link to pattern'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of the Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='yarn',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stash.yarn', verbose_name='Yarn in this project'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='amount',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='How much yarn you have? (g)'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='body',
            field=models.TextField(blank=True, verbose_name='Notes about the yarn'),
        ),
    ]
